"use client";

import Badge from "@/components/ui/badge";
import { Container } from "@/components/ui/Container";
import DataTable from "@/components/ui/dataTable";
import Input from "@/components/ui/input";
import { ColumnDef } from "@tanstack/react-table";
import { useEffect, useState } from "react";

type ReportType = {
  _id: string;
  title: string;
  type: "Sales" | "User" | "Product";
  generatedBy: string;
  createdAt: string;
  status: "Pending" | "Completed" | "Failed";
};

// Mock report data
const mockReports: ReportType[] = [
  {
    _id: "1",
    title: "Monthly Sales Report",
    type: "Sales",
    generatedBy: "Admin",
    createdAt: "2025-09-28",
    status: "Completed",
  },
  {
    _id: "2",
    title: "User Registration Report",
    type: "User",
    generatedBy: "Manager",
    createdAt: "2025-09-27",
    status: "Pending",
  },
  {
    _id: "3",
    title: "Product Stock Report",
    type: "Product",
    generatedBy: "Admin",
    createdAt: "2025-09-26",
    status: "Failed",
  },
  {
    _id: "4",
    title: "Quarterly Sales Report",
    type: "Sales",
    generatedBy: "Manager",
    createdAt: "2025-09-25",
    status: "Completed",
  },
];

// Status badge UI
const StatusBadge = ({ status }: { status: ReportType["status"] }) => {
  const statusVariant =
    status === "Pending"
      ? "warning"
      : status === "Failed"
      ? "danger"
      : status === "Completed"
      ? "success"
      : "danger";

  return <Badge variant={statusVariant}>{status}</Badge>;
};

const columns: ColumnDef<ReportType>[] = [
  {
    accessorKey: "_id",
    header: "ID",
    cell: ({ row }) => (
      <span className="font-medium">{row.getValue("_id")}</span>
    ),
  },
  {
    accessorKey: "title",
    header: "Title",
    cell: ({ row }) => <span>{row.getValue("title")}</span>,
  },
  {
    accessorKey: "type",
    header: "Type",
    cell: ({ row }) => (
      <span className="text-gray-500">{row.getValue("type")}</span>
    ),
  },
  {
    accessorKey: "generatedBy",
    header: "Generated By",
    cell: ({ row }) => <span>{row.getValue("generatedBy")}</span>,
  },
  {
    accessorKey: "createdAt",
    header: "Created At",
    cell: ({ row }) => (
      <span className="text-gray-500">{row.getValue("createdAt")}</span>
    ),
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => {
      return <StatusBadge status={row.getValue("status")} />;
    },
  },
];

const ReportList = () => {
  const [search, setSearch] = useState("");
  const [reports, setReports] = useState<ReportType[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);

    setTimeout(() => {
      // filter
      const filtered = mockReports.filter((report) =>
        report.generatedBy.toLowerCase().includes(search.toLowerCase())
      );

      setReports(filtered);
      setLoading(false);
    }, 500);
  }, [search]);
  return (
    <Container>
      {" "}
      <div className="p-6">
        <h1 className="mb-4 text-xl font-semibold">Reports</h1>
        {/* Search */}
        <div className="flex gap-3 mb-6 w-full">
          <Input
            placeholder="Search report..."
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
            }}
            className="flex-1"
          />
        </div>
        <DataTable
          loading={loading}
          size="lg"
          columns={columns}
          data={reports}
        />
      </div>
    </Container>
  );
};

export default ReportList;
