"use client";

import DataTable from "@/components/ui/dataTable";
import { ColumnDef } from "@tanstack/react-table";

type ReportType = {
  _id: string;
  title: string;
  type: "Sales" | "User" | "Product";
  generatedBy: string;
  createdAt: string;
  status: "Pending" | "Completed" | "Failed";
};

// Mock report data
const mockReports: ReportType[] = [
  {
    _id: "1",
    title: "Monthly Sales Report",
    type: "Sales",
    generatedBy: "Admin",
    createdAt: "2025-09-28",
    status: "Completed",
  },
  {
    _id: "2",
    title: "User Registration Report",
    type: "User",
    generatedBy: "Manager",
    createdAt: "2025-09-27",
    status: "Pending",
  },
  {
    _id: "3",
    title: "Product Stock Report",
    type: "Product",
    generatedBy: "Admin",
    createdAt: "2025-09-26",
    status: "Failed",
  },
  {
    _id: "4",
    title: "Quarterly Sales Report",
    type: "Sales",
    generatedBy: "Manager",
    createdAt: "2025-09-25",
    status: "Completed",
  },
];

const columns: ColumnDef<ReportType>[] = [
  {
    accessorKey: "_id",
    header: "ID",
    cell: ({ row }) => (
      <span className="font-medium">{row.getValue("_id")}</span>
    ),
  },
  {
    accessorKey: "title",
    header: "Title",
    cell: ({ row }) => <span>{row.getValue("title")}</span>,
  },
  {
    accessorKey: "type",
    header: "Type",
    cell: ({ row }) => (
      <span className="text-gray-500">{row.getValue("type")}</span>
    ),
  },
  {
    accessorKey: "generatedBy",
    header: "Generated By",
    cell: ({ row }) => <span>{row.getValue("generatedBy")}</span>,
  },
  {
    accessorKey: "createdAt",
    header: "Created At",
    cell: ({ row }) => (
      <span className="text-gray-500">{row.getValue("createdAt")}</span>
    ),
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => {
      const status = row.getValue("status") as ReportType["status"];
      let color = "text-gray-500";
      if (status === "Pending") color = "text-yellow-500";
      if (status === "Completed") color = "text-green-500";
      if (status === "Failed") color = "text-red-500";
      return <span className={color}>{status}</span>;
    },
  },
];

const ReportList = () => {
  return (
    <div className="p-6">
      <h1 className="mb-4 text-xl font-semibold">Reports</h1>
      <DataTable columns={columns} data={mockReports} />
    </div>
  );
};

export default ReportList;
