import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/NavBar";
import Sidebar from "@/components/layout/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar at the top */}

        {/* Main layout */}
        <div className="flex ">
          {/* Sidebar on desktop */}
          <Sidebar />

          {/* Main content area */}
          <main className="flex-1 bg-background text-foreground  min-h-screen">
            <Navbar />
            {children}
            {/* <Footer /> */}
          </main>
        </div>

        {/* Footer at the bottom */}
      </body>
    </html>
  );
}
